# Site settings
title:            "Out of Focus" # 添加博客标题
author:           sardine2 # 添加你的名字
logo:             logo.png # 添加博客 Logo
avatar:           avatar.png # 添加你的头像
favicon:          favicon.ico # 添加用于显示于浏览器 Tab 上的博客图标
email:            sardine2@yeah.com
description: >    # 主题简介，可改为博客描述
                   你是一个意外。

url:              "wangshourong.sardine2.com" # 添加域名（不需要 http:// 前缀），或使用「/」作为博客根链接，
baseurl:          "blog" # the subpath of your site, e.g. /blog/

twitter:          # 添加你的 Twitter 用户名
github:           sardine2 # 添加你的 GitHub 用户名
disqus:           # 添加你的 Disqus 评论工具站点名

permalink:        pretty
paginate:         5

# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

gems:
  - jekyll-sitemap
  - jekyll-paginate
